/* Execute this SQL file against a database to prepare tables for use with IRCBot. */

DROP TABLE IF EXISTS Quotes;
DROP TABLE IF EXISTS Seen;

CREATE TABLE IF NOT EXISTS Quotes(ID INT PRIMARY KEY AUTO_INCREMENT, Nick VARCHAR(255) NOT NULL, Date DATETIME NOT NULL, Channel VARCHAR(32) NOT NULL, Quote VARCHAR(255) NOT NULL);
CREATE TABLE IF NOT EXISTS Seen(ID INT PRIMARY KEY AUTO_INCREMENT, Nick VARCHAR(255) NOT NULL, Date DATETIME NOT NULL, Channel VARCHAR(32) NOT NULL);